server:
  port: 8073
spring:
  application:
    name: SpringAIChatClient
  ai:
    chat:
      client:
        enabled: false
    deepseek:
      base-url: https://api.deepseek.com
      api-key: ${deepseek.api-key}
      # 跳过 SSL 证书验证(仅开发环境使用)
      ssl:
        verify: false
      chat:
        options:
          model: deepseek-chat
          # 介于 0-2 之间,0 表示随机性很小,2 表示随机性很大
          temperature: 0.8
