server:
  port: 8081
spring:
  application:
    name: LangChain4JDemo
  data:
    redis:
      jedis:
        pool:
          enabled: true
      host: 172.30.47.249
      password: 1qaz2wsx3edc
      port: 6379
langchain4j:
  open-ai:
    chat-model:
      api-key: ${deepseek.api-key}
      model-name: deepseek-chat
      base-url: https://api.deepseek.com
      log-requests: true
      log-responses: true
    streaming-chat-model:
      api-key: ${deepseek.api-key}
      model-name: deepseek-chat
      base-url: https://api.deepseek.com
      log-requests: true
      log-responses: true