server:
  port: 8070
spring:
  application:
    name: SpringAIQuickStart
  ai:
    deepseek:
      base-url: https://api.deepseek.com
      api-key: ${deepseek.api-key}
      chat:
        options:
          model: deepseek-chat
          # 介于 0-2 之间，0 表示随机性很小，2 表示随机性很大
          temperature: 0.8
