server:
  port: 8072
spring:
  application:
    name: SpringAIChatMemory
  ai:
    chat:
      client:
        enabled: false
      memory:
        repository:
          jdbc:
            # 当前数据库是 MariaDB/MySQL，会记在 schema-mariadb.sql 初始化脚本，自行创建表 SPRING_AI_CHAT_MEMORY表
            platform: mysql
            initialize-schema:
    deepseek:
      base-url: https://api.deepseek.com
      api-key: ${deepseek.api-key}
      # 跳过 SSL 证书验证(仅开发环境使用)
      ssl:
        verify: false
      chat:
        options:
          model: deepseek-chat
          # 介于 0-2 之间,0 表示随机性很小,2 表示随机性很大
          temperature: 0.8
  datasource:
    hikari:
      # 确保每条 JDBC 连接都使用 utf8mb4字符集并指定utf8mb4_unicode_ci排序
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
    url: jdbc:mysql://172.30.47.249:3306/chat_memory?useUnicode=true&characterEncoding=utf-8&connectionCollation=utf8mb4_unicode_ci
    username: wanyun_ppc_test
    password: hLGQK4H3nz9h0f2qkfuf7lm0nYzv1ll9
    driver-class-name: com.mysql.cj.jdbc.Driver
